tabvars <- c("country" , 
             "Age", 
             "BMI", 
             "SBPav", 
             "DBPav", 
             "Ethnicity", 
             "Marital", 
             "Partnered", 
             "Education", 
             "University", 
             "Occupation", 
             "Working", 
             "Living", 
             "Cohabitation", 
             "Income", 
             "Low.income", 
             "Infertility.History", 
             "Fertility.Treatment", 
             "Anaemia", 
             "IBD", 
             "Coeliac.Disease",
             "RA", 
             "Epilepsy", 
             "IBS", 
             "Asthma", 
             "PCOS", 
             "Depression.History", 
             "Smoking.pre", 
             "Smoking.tri1", 
             "Smoking", 
             "Alcohol.pre", 
             "Alcohol.tri1", 
             "Alcohol", 
             "Drugs.pre", 
             "Drugs.tri1", 
             "Drugs", 
             "Delivery", 
             "Baby.sex")

modvars <- c("country" , 
             "Age", 
             "BMI", 
             "SBPav", 
             #"Ethnicity", 
             "Partnered", 
             "University", 
             "Working", 
             #"Cohabitation", 
             "Low.income", 
             "Infertility.History", 
             #"Fertility.Treatment", 
             "Anaemia", 
             "IBD", 
             "Coeliac.Disease",
             "RA", 
             "Epilepsy", 
             "IBS", 
             "Asthma", 
             "PCOS", 
             "Depression.History", 
             "Smoking", 
             "Alcohol", 
             "Drugs", 
             "Baby.sex")


outvars_binary <- c("Preeclampsia", "Severe.maternal.PE", 
             "GH", "GDM", "Placental.Abruption", 
             "Emergency.SC", "SGA", "LGA",                                     
             "Spontaneous.Preterm.Birth", "Neonatal.morbidity", 
             "Grouping.variable.Complicated.Pregnancy") 
             
outvars_ordinal <- c("TOTAL.SCORE", "OUTCOME_Grp", "OUTCOME_Grp2")