```{r predor, cache=cacheon}

ormod <- function(outvar, outname = NULL, data = cleandata, adjvars = modvars) {
  if (is.null(outname)) outname <- outvar

  # adj
  ormod <- glm(formula(paste0(outvar, "== '1' ~ ", paste(adjvars, collapse = " + "))),
    data = data,
    family = binomial(link = "logit")
  )

  sormod <- summary(ormod)

  nval <- nrow(sormod$coefficients)
  outor <- bind_cols(
    Variable = rownames(sormod$coefficients)[2:nval],
    adjor = paste0(
      fn(exp(sormod$coefficients[2:nval, 1]), 1), " (",
      fn(exp(sormod$coefficients[2:nval, 1] - global_z05 * sormod$coefficients[2:nval, 2]), 1), "-",
      fn(exp(sormod$coefficients[2:nval, 1] + global_z05 * sormod$coefficients[2:nval, 2]), 1), "), ",
      fn(sormod$coefficients[2:nval, 4], dig = 3, p = TRUE)
    )
  )

  outor <- outor %>%
    mutate(crudeor = NA_character_) %>%
    select(Variable, crudeor, adjor)

  # crude
  for (i in seq_along(adjvars)) {
    ormod <- glm(formula(paste0(outvar, "== '1' ~ ", adjvars[i])),
      data = data,
      family = binomial(link = "logit")
    )

    sormod <- summary(ormod)

    nval <- nrow(sormod$coefficients)
    outor_crude <- bind_cols(
      Variable = rownames(sormod$coefficients)[2:nval],
      crudeor = paste0(
        fn(exp(sormod$coefficients[2:nval, 1]), 1), " (",
        fn(exp(sormod$coefficients[2:nval, 1] - global_z05 * sormod$coefficients[2:nval, 2]), 1), "-",
        fn(exp(sormod$coefficients[2:nval, 1] + global_z05 * sormod$coefficients[2:nval, 2]), 1), "), ",
        fn(sormod$coefficients[2:nval, 4], dig = 3, p = TRUE)
      )
    )

    outor <- full_join(outor, outor_crude, by = "Variable") %>%
      mutate(crudeor = coalesce(crudeor.x, crudeor.y)) %>%
      select(Variable, crudeor, adjor)
  }

  colnames(outor) <- sanitize_text(c("Variable", "Crude OR (95% CI), p-value", "Adjusted OR (95% CI), p-value"))

  outor <- outor %>%
    mutate(
      Variable = str_remove(Variable, "1"),
      Variable = sanitize_text(Variable)
    )

  default_kable(outor,
    caption = sanitize_text(paste0("Association with pregnancy outcome - ", outname)),
    longtable = TRUE,
    escape = FALSE
  )
}

pormod <- function(outvar, outname = NULL, data = cleandata, adjvars = modvars) {
  if (is.null(outname)) outname <- outvar

  mod <- polr(formula(paste0(outvar, " ~ ", paste(adjvars, collapse = " + "))),
    data = data,
    Hess = TRUE
  )

  smod <- summary(mod)

  nval <- length(mod$coefficients)

  p <- (pnorm(abs(smod$coefficients[, "t value"]), lower.tail = FALSE) * 2)[1:nval]
  outor <- bind_cols(
    Variable = rownames(smod$coefficients)[1:nval],
    adjor = paste0(
      fn(exp(smod$coefficients[1:nval, 1]), 1), " (",
      fn(exp(smod$coefficients[1:nval, 1] - global_z05 * smod$coefficients[1:nval, 2]), 1), "-",
      fn(exp(smod$coefficients[1:nval, 1] + global_z05 * smod$coefficients[1:nval, 2]), 1), "), ",
      fn(p, dig = 3, p = TRUE)
    )
  )

  outor <- outor %>%
    mutate(crudeor = NA_character_) %>%
    select(Variable, crudeor, adjor)

  # crude
  for (i in seq_along(adjvars)) {
    mod <- polr(formula(paste0(outvar, " ~ ", adjvars[i])),
      data = data,
      Hess = TRUE
    )

    smod <- summary(mod)

    nval <- length(mod$coefficients)

    p <- (pnorm(abs(smod$coefficients[, "t value"]), lower.tail = FALSE) * 2)[1:nval]
    outor_crude <- bind_cols(
      Variable = rownames(smod$coefficients)[1:nval],
      crudeor = paste0(
        fn(exp(smod$coefficients[1:nval, 1]), 1), " (",
        fn(exp(smod$coefficients[1:nval, 1] - global_z05 * smod$coefficients[1:nval, 2]), 1), "-",
        fn(exp(smod$coefficients[1:nval, 1] + global_z05 * smod$coefficients[1:nval, 2]), 1), "), ",
        fn(p, dig = 3, p = TRUE)
      )
    )

    outor <- full_join(outor, outor_crude, by = "Variable") %>%
      mutate(crudeor = coalesce(crudeor.x, crudeor.y)) %>%
      select(Variable, crudeor, adjor)
  }

  colnames(outor) <- sanitize_text(c("Variable", "Crude OR (95% CI), p-value", "Adjusted OR (95% CI), p-value"))

  outor <- outor %>%
    mutate(
      Variable = str_remove(Variable, "1"),
      Variable = sanitize_text(Variable)
    )

  default_kable(outor,
    caption = sanitize_text(paste0("Association with pregnancy outcome - ", outname)),
    longtable = TRUE,
    escape = FALSE
  )
}
```

\clearpage

```{r predorprint1, dependson="predor", cache=cacheon}
ormod("Preeclampsia...226", outname = "Maternal outcome Preeclampsia")
```

\clearpage

```{r predorprint2, dependson="predor", cache=cacheon}
ormod("Gestational.hypertension_GH", outname = "Maternal outcome Gestational hypertension")
```

\clearpage

```{r predorprint3, dependson="predor", cache=cacheon}
ormod("Gestational.diabetes_GDM", outname = "Maternal outcome Gestational diabetes")
```

\clearpage

```{r predorprint4, dependson="predor", cache=cacheon}
ormod("Emergency.SC", outname = "Maternal outcome Emergency SC")
```

\clearpage

```{r predorprint5, dependson="predor", cache=cacheon}
ormod("Placental.Abruption...238", outname = "Maternal outcome Placental abruption", adjvars = modvars2)
```

\clearpage

```{r predorprint6, dependson="predor", cache=cacheon}
pormod("Gest_age_cat", outname = "Neonatal outcome Gest age Delivery", cleandata %>% filter(`Intrauterine.fetal.death.REMOVE=1` != 1))
```

\clearpage

```{r predorprint7, dependson="predor", cache=cacheon}
ormod("Gest_age_postterm", outname = "Neonatal outcome Gest age Delivery postterm", cleandata %>% filter(`Intrauterine.fetal.death.REMOVE=1` != 1))
```

\clearpage

```{r predorprint8, dependson="predor", cache=cacheon}
ormod("Customised.Birthweight.Centile_sga",
  outname = "Neonatal outcome Customized birth centile SGA",
  cleandata %>% filter(`Intrauterine.fetal.death.REMOVE=1` != 1)
)
```

\clearpage

```{r predorprint9, dependson="predor", cache=cacheon}
ormod("Customised.Birthweight.Centile_lga",
  outname = "Neonatal outcome Customized birth centile LGA",
  cleandata %>% filter(`Intrauterine.fetal.death.REMOVE=1` != 1)
)
```

\clearpage

```{r predorprint10, dependson="predor", cache=cacheon}
pormod("Cord.arterial.pH_cat_imp",
  outname = "Neonatal outcome Cord artery pH",
  cleandata %>% filter(`Intrauterine.fetal.death.REMOVE=1` != 1)
)
```

\clearpage

```{r predorprint11, dependson="predor", cache=cacheon}
pormod("Cord.artery.BE_cat_imp",
  outname = "Neonatal outcome Cord artery BE",
  cleandata %>% filter(`Intrauterine.fetal.death.REMOVE=1` != 1)
)
```

\clearpage

```{r predorprint12, dependson="predor", cache=cacheon}
pormod("Apgar.score.1.min_cat", outname = "Neonatal outcome Apgar 1 min", cleandata %>% filter(`Intrauterine.fetal.death.REMOVE=1` != 1))
```

\clearpage

```{r predorprint13, dependson="predor", cache=cacheon}
pormod("Apgar.score.5.min_cat", outname = "Neonatal outcome Apgar 5 min", cleandata %>% filter(`Intrauterine.fetal.death.REMOVE=1` != 1))
```

\clearpage

```{r predorprint14, dependson="predor", cache=cacheon}
ormod("Intubation.at.birth", outname = "Intubation", cleandata %>% filter(`Intrauterine.fetal.death.REMOVE=1` != 1))
```
